version: "3.8"

services:
  ssh-key-generator:
    image: ghcr.io/hueske-digital/sshkey-generator:latest
    environment:
      - SSH_HOST
      - SSH_HOSTNAME
      - SSH_USER
      - SSH_PORT
    volumes:
      - ssh_data:/root/.ssh

  backup:
    image: garethgeorge/backrest:latest-alpine
    hostname: docker
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
      - TMPDIR=/tmp
      - NOTIFY_URL
    volumes:
      - app_data:/data
      - app_config:/config
      - app_cache:/cache
      - app_tmp:/tmp
      - ssh_data:/root/.ssh
      - /var/lib/docker/volumes:/mnt/volumes
      - $HOME:/mnt/home
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/bin:/scripts:ro
    networks:
      proxy_apps:

volumes:
  app_data:
  app_config:
  app_cache:
  app_tmp:
  ssh_data:

networks:
  proxy_apps:
    name: proxy_apps
    external: true
