version: "3.8"

services:
  ssh-key-generator:
    image: alpine
    volumes:
      - ssh_data:/root/.ssh
    command: >
      /bin/sh -c "
      if [ ! -f /root/.ssh/id_ed25519 ]; then
        apk add --no-cache openssh;
        mkdir -p /root/.ssh;
        ssh-keygen -t ed25519 -f /root/.ssh/id_ed25519 -q -N '';
        echo 'SSH keys generated.';
      fi;
      echo 'Host *' > /root/.ssh/config;
      echo '  StrictHostKeyChecking no' >> /root/.ssh/config;
      echo '  ServerAliveInterval 60' >> /root/.ssh/config;
      echo '  ServerAliveCountMax 240' >> /root/.ssh/config;
      chmod 700 /root/.ssh;
      chmod 600 /root/.ssh/id_ed25519;
      chmod 644 /root/.ssh/id_ed25519.pub;
      "

  backup:
    image: mazzolino/restic
    hostname: docker
    restart: unless-stopped
    env_file:
      - $PWD/.env
    volumes:
      - ssh_data:/run/secrets/.ssh:ro
      - /var/lib/docker/volumes:/mnt/volumes
      - $HOME:/mnt/home
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: ["/sbin/tini", "--", "/bin/sh", "-c", "unset PRUNE_CRON; /entrypoint"]

  prune:
    image: mazzolino/restic
    hostname: docker
    volumes:
      - ssh_data:/run/secrets/.ssh:ro
    env_file:
      - $PWD/.env
    restart: unless-stopped
    entrypoint: ["/sbin/tini", "--", "/bin/sh", "-c", "unset BACKUP_CRON; unset PRE_COMMANDS; unset POST_COMMANDS_EXIT; unset POST_COMMANDS_SUCCESS; /entrypoint"]

volumes:
  ssh_data: