version: "3.8"

services:
  ssh-key-generator:
    image: ghcr.io/hueske-digital/sshkey-generator:latest
    volumes:
      - ssh_data:/root/.ssh

  backup:
    image: mazzolino/restic
    hostname: docker
    restart: unless-stopped
    environment:
      - TZ
      - RUN_ON_STARTUP
      - RESTIC_REPOSITORY
      - RESTIC_PASSWORD
      - RESTIC_BACKUP_SOURCES
      - RESTIC_BACKUP_ARGS
      - RESTIC_FORGET_ARGS
      - BACKUP_CRON
      - NOTIFY_URL
      - PRE_COMMANDS
      - POST_COMMANDS_INCOMPLETE
      - POST_COMMANDS_FAILURE
      - POST_COMMANDS_EXIT
    volumes:
      - $PWD/bin:/scripts
      - ssh_data:/run/secrets/.ssh:ro
      - /var/lib/docker/volumes:/mnt/volumes
      - $HOME:/mnt/home
      - /var/run/docker.sock:/var/run/docker.sock

  prune:
    image: mazzolino/restic
    hostname: docker
    environment:
      - TZ
      - RUN_ON_STARTUP
      - RESTIC_REPOSITORY
      - RESTIC_PASSWORD
      - PRUNE_CRON
    volumes:
      - ssh_data:/run/secrets/.ssh:ro
    restart: unless-stopped

  check:
    image: mazzolino/restic
    hostname: docker
    environment:
      - TZ
      - RUN_ON_STARTUP
      - RESTIC_REPOSITORY
      - RESTIC_PASSWORD
      - RESTIC_CHECK_ARGS
      - CHECK_CRON
    volumes:
      - ssh_data:/run/secrets/.ssh:ro
    restart: unless-stopped

volumes:
  ssh_data: